---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  roles:
    - role: bossjones-ipv6
    # - role: ksylvan.docker

    # sudo mkdir -p /etc/dnf/vars
    # echo 27 | sudo tee /etc/dnf/vars/docker_releasever
    # sudo sed -i 's/\$releasever/$docker_releasever/g' /etc/yum.repos.d/docker-ce.repo

    - role: motd
    - role: bossjones-firewalld
    - role: mjanser.powerline
    - role: joshualund.golang
    - role: common
      theme: "powerline-plain"
      repository: https://github.com/revans/bash-it.git
      version: master
      aliases:
        - general
      plugins:
        - base
        - history
      completions:
        - git
    - role: bossjones-cli-tools

  pre_tasks:

    - name: make sure dnf-plugins.core installed
      dnf:
        name: dnf-plugins-core
        state: present

    # - name: install docker repository
    #   command: curl -L https://download.docker.com/linux/fedora/docker-ce.repo > /etc/yum.repos.d/docker-ce.repo; dnf update -y

    - name: make sure docker from distro is not installed
      dnf:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker
        - docker-common
        - container-selinux
        - docker-selinux
        - docker-engine

    - name: show duplicates
      shell: 'dnf list docker-ce  --showduplicates | sort -r'

    - name: install docker
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce
        - python-docker-py
        - python-pip

    # systemctl start docker
    # usermod -aG adm,tty,audio vagrant
    #  sudo chkconfig docker on
    # create alias: alias docker="sudo /usr/bin/docker"
    # sudo gpasswd -a $USER docker
    # add to sudoers: %adm    ALL=(ALL)       NOPASSWD: /usr/bin/docker

    - name: Fail if Ansible is ancient
      fail: msg="We need Ansible >= 2.0. Please update your kit. 'pip install -U Ansible'"
      when: ansible_version.major < 2
      tags:
        - always

    - name: Include vars from local-configure.yml if found
      include_vars: "{{ item }}"
      with_first_found:
       - local-configure.yml
       - null.yml

    - name: pre install system ruby
      dnf: name={{item}} state=present
      with_items:
        - ruby

  tasks:

    - name: Set timezone variables
      tags: timezone
      copy: content={{ timezone|default("UTC\n") }}
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone

  handlers:
    - name: update timezone
      when: ansible_os_family == 'RedHat'
      file: src=/usr/share/zoneinfo/{{ timezone|default("UTC\n") }}  dest=/etc/localtime state=link force=yes
